/* Catálogo de correos ya armados. Sumar uno = agregar un objeto a EMAILS.
   Cada correo respeta el layout y distancias del original; el estilo (glass,
   gradientes, coral) lo aplica el render de secciones según patrones.md. */

import { Section } from './email-templates';

export interface EmailTemplate {
  id: string;        // slug para la URL
  name: string;      // nombre visible
  subject: string;   // asunto del correo
  desc: string;      // descripción corta para la card
  category?: string; // agrupa la card en el catálogo (ej. "En vivo")
  stage?: string;     // paso dentro del flujo de la categoría (ej. "Negociación"), pinta el stepper
  sections: Section[];
}

const ICON = {
  calendar: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-calendar.png',
  search: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-search.png',
  eye: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-eye.png',
  cards: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-cards.png',
  bank: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-bank-building.png',
  phone: 'https://cdn.vmcsubastas.com/services/boletin/assets/phone-bcp.png',
};

// demo del design system Concorde (mismo asset que usan OfferCard/Detalle/Sala en concorde/bloques);
// swap por fotos reales del vehículo/ofertas cuando estén disponibles en el CDN
const DEMO_CAR = 'https://concorde-v2-theta.vercel.app/demo/bronco.jpg';
const PLACEHOLDER = { car: DEMO_CAR, thumb: DEMO_CAR, offer: DEMO_CAR };

// helper local: no repetir id/type a mano
const S = (type: Section['type'], content: Record<string, string>): Section => ({
  id: `${type}-${Math.random().toString(36).slice(2, 7)}`, type, content,
});
const SP = (height: string) => S('spacer', { height });

export const EMAILS: EmailTemplate[] = [
  {
    id: 'fee-subascoins',
    name: 'Fee Notice — SubasCoins',
    subject: 'Información importante sobre tus adquisiciones de SubasCoins',
    desc: 'Announces the new gateway fee and the fee-free options (BCP / CUU).',
    sections: [
      // layout y distancias del correo original
      S('title', { eyebrow: '', text: 'Información importante sobre tus adquisiciones de SubasCoins' }),
      SP('30'),
      S('text', { text: 'Queremos contarte que hemos realizado una actualización en nuestros Términos y Condiciones relacionada con la adquisición de SubasCoins en plataforma.' }),
      SP('20'),
      S('panel', {
        title: 'A partir del **1 de Julio** del presente año',
        body: 'Las compras de SubasCoins realizadas a través de la plataforma utilizando tarjeta de Crédito o Débito podrán incluir un **Fee por uso de pasarela**, asociado al procesamiento de la transacción.',
        iconUrl: ICON.calendar, badge: '', imageUrl: '', imageW: '85', imageH: '57',
      }),
      SP('20'),
      S('features', {
        heading: '¿Qué debes tener en cuenta sobre este Fee?',
        i1: ICON.search, t1: 'El costo del fee equivale al [[3.9%]] del monto de tu adquisición de SubasCoins',
        i2: ICON.eye, t2: 'Se te mostrará de manera clara y desagregada antes de realizar el pago',
        i3: ICON.cards, t3: 'Si tu tarjeta es en soles, el tipo de cambio será determinado por tu proveedor',
      }),
      SP('20'),
      S('panel', {
        title: 'Opciones **SIN FEE** por uso de pasarela',
        body: 'Puedes realizar tu recarga de saldo en dólares a través de ventanilla, agente o app del banco BCP utilizando tu CUU. Esta operación carece del cobro de este Fee.',
        iconUrl: ICON.bank, badge: 'white', imageUrl: ICON.phone, imageW: '85', imageH: '57',
      }),
      SP('30'),
    ],
  },
  {
    id: 'listo-participar',
    name: 'Ready to Bid — Participation',
    subject: '¡Listo para participar en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Confirms participation: details (date, seller, consignment) + live-room reminder.',
    category: 'En vivo',
    stage: 'Inicio',
    sections: [
      // {{...}} = merge tags (se reemplazan en tu plataforma); **...** = acento
      S('title', { eyebrow: '', text: '¡Listo para participar en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario .Ejem: Gabriel Bruno}}, datos de tu participación:' }),
      SP('14'),
      S('details', {
        l1: 'Fecha y hora:', v1: 'Miércoles, 11 de octubre - 2:00 p.m.',
        l2: 'Vendedor:', v2: 'Financiera Automotriz',
        l3: 'Consignación:', v3: '50 SubasCoins',
      }),
      SP('16'),
      S('divider', {}),
      SP('16'),
      S('note', {
        title: 'Recuerda:',
        body: 'Al consignar, eres responsable de asegurar tu conexión a sala "En Vivo" y de participar enviando, al menos, un bid válido durante el proceso, o serás sancionado.',
      }),
      SP('30'),
    ],
  },
  {
    id: 'oportunidad-compra',
    name: 'Purchase Opportunity — 2nd/3rd Place',
    subject: '¡Tienes oportunidad de compra en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies 2nd/3rd-place bidders of a purchase opportunity and explains eligibility conditions.',
    category: 'En vivo',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Tienes oportunidad de compra en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('14'),
      S('text', { text: '¡Felicidades estas entre los __3 mejores postores__! __Te notificaremos en caso se active tu oportunidad de compra.__' }),
      SP('16'),
      S('text', { text: '**Recuerda:** Tu garantía se mantendrá consignada hasta que el proceso de venta de la oferta haya finalizado. **¡Aún hay una oportunidad de ganar con VMC Subastas!**' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es la oportunidad de compra?**' }),
      SP('12'),
      S('text', { text: 'La oportunidad de compra es __una condición obtenida por el mejor postor__ en una oferta \'En Vivo\' con reserva y por el __2do o 3er lugar en un proceso sin reserva__.' }),
      SP('12'),
      S('text', { text: 'En caso de **activarse la oportunidad de compra** el participante adquirirá las __responsabilidades de ganador directo habilitado__ siendo responsable de seguir con el proceso de compra, bajo pena de sanción en caso de incumplimiento.' }),
      SP('30'),
    ],
  },
  {
    id: 'ganador-directo',
    name: 'Direct Winner — Purchase',
    subject: '¡Eres el Ganador Directo en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the direct winner, prompts to start the purchase, and states the sanctions.',
    category: 'En vivo',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Eres el Ganador Directo en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario .Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! Estás a un paso de cumplir tus metas. __Inicia el proceso de compra__ ingresando a tu zona de usuario.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('text', { text: 'En cualquier caso, cuando el ganador directo habilitado haya **incumplido con alguna de sus responsabilidades**, será sancionado con la pérdida de 75 Puntos.' }),
      SP('12'),
      S('text', { text: 'VMC SUBASTAS también procederá a exigir el **pago equivalente a la comisión** establecido como contraprestación por el uso de la Billetera brindada, detrayéndola si fuese posible de la Billetera automáticamente; cuando el usuario carezca de fondos suficientes para cubrir el total de la comisión, se procederá a amortizar de manera parcial la deuda correspondiente detrayendo el íntegro de los fondos en Billetera del ganador, por lo que su usuario mantendrá una deuda en plataforma y su cuenta permanecerá restringida.' }),
      SP('30'),
    ],
  },
  {
    id: 'mejor-postor',
    name: 'Best Bidder Notification',
    subject: '¡Eres el Mejor Postor en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the current best bidder and explains what being top bidder means.',
    category: 'En vivo',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Eres el Mejor Postor en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades, estás a un paso para cumplir tus metas! Te notificaremos cuando tengas la respuesta del vendedor y __tu garantía se mantendrá consignada__ hasta ese momento.' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué significa ser mejor postor?**' }),
      SP('12'),
      S('text', { text: '__Mejor postor:__ Es quien realiza la mejor propuesta en una oferta "En Vivo" con Precio reserva, por lo cual su propuesta pasa a evaluación con el vendedor y este tendrá hasta **10 días hábiles** dar una respuesta a dicho ganador.' }),
      SP('30'),
    ],
  },
  {
    id: 'opcion-compra',
    name: 'Purchase Option Notification',
    subject: '¡Tienes opción de compra en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the buyer the seller granted a purchase option and prompts them to accept it.',
    category: 'En vivo',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Tienes opción de compra en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades el vendedor te dio la **opción de compra**! Ingresa a tu zona de usuario para **aceptarla**.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es la opción de compra?**' }),
      SP('12'),
      S('text', { text: 'La opción de compra es una __condicional que todo vendedor podrá activar__ cuando crea conveniente.' }),
      SP('12'),
      S('text', { text: 'El participante, a quien se le dé la opción de compra y acepte la misma asumirá todas las __responsabilidades de un ganador directo habilitado__.' }),
      SP('12'),
      S('text', { text: 'El participante podrá rechazar dicha opción, libre de sanciones asociadas.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta',
    name: 'Counteroffer Notification',
    subject: '¡Recibiste una contrapropuesta en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the top bidder of a seller counteroffer and explains the counteroffer mechanic.',
    category: 'En vivo',
    stage: 'Negociación',
    sections: [
      S('title', { eyebrow: '', text: '¡Recibiste una contrapropuesta en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu zona de usuario y **revisa la contrapropuesta del vendedor**!' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es una contrapropuesta?**' }),
      SP('12'),
      S('text', { text: 'El vendedor se reserva el derecho de declinar la propuesta del mejor postor y **optar por hacerle una contrapropuesta sobre el monto ofrecido**.' }),
      SP('12'),
      S('text', { text: 'En caso aceptes la contrapropuesta asumirás las **responsabilidades del ganador directo habilitado**.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-rechazada',
    name: 'Rejected Proposal Notification',
    subject: '¡Rechazaste la propuesta en la oferta {{Toyota Yaris 2018}}!',
    desc: 'Confirms the bidder rejected the seller counteroffer and their consignment was released.',
    category: 'En vivo',
    stage: 'Negociación',
    sections: [
      S('title', { eyebrow: '', text: '¡Rechazaste la propuesta en la oferta {{Toyota Yaris 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Has rechazado la propuesta de __{{vendedor}}__ en la oferta **{{Toyota Yaris 2018}}**. Ahora te encuentras fuera del proceso de compra.' }),
      SP('16'),
      S('text', { text: '**Tu consignación fue liberada a tu billetera.**' }),
      SP('30'),
    ],
  },
  {
    id: 'habilitado-comprar',
    name: 'Enabled to Buy Notification',
    subject: '¡Has sido habilitado en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the participant they are enabled to buy, prompts the purchase flow, and states the sanctions.',
    category: 'En vivo',
    stage: 'Habilitación',
    sections: [
      S('title', { eyebrow: '', text: '¡Has sido habilitado en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades estás **habilitado para comprar**! __Inicia el proceso de compra__ ingresando a tu zona de usuario.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('text', { text: 'En cualquier caso, cuando el ganador directo habilitado haya **incumplido con alguna de sus responsabilidades**, será sancionado con la pérdida de 75 Puntos.' }),
      SP('12'),
      S('text', { text: 'VMC SUBASTAS también procederá a exigir el **pago equivalente a la comisión** establecida como contraprestación por el uso del servicio brindado, detrayéndola si fuese posible de su Billetera automáticamente; cuando el usuario carezca de fondos suficientes para cubrir el total de la comisión, se procederá a amortizar de manera parcial la deuda correspondiente detrayendo el íntegro de los fondos en Billetera del ganador, por lo que el usuario mantendrá una deuda en plataforma y su cuenta permanecerá restringida.' }),
      SP('30'),
    ],
  },
  {
    id: 'oferta-terminada',
    name: 'Offer Ended Notification',
    subject: '¡Oferta terminada!',
    desc: 'Notifies bidders the seller rejected the top proposal and the offer closed.',
    category: 'En vivo',
    stage: 'Cierre',
    sections: [
      S('title', { eyebrow: '', text: '¡Oferta terminada!' }),
      SP('24'),
      S('text', { text: '¡El **{{Vendedor}}** rechazó la propuesta del **{{C.U.U}}** en la oferta **{{Toyota Yaris 2018}}**!' }),
      SP('30'),
    ],
  },
  {
    id: 'oferta-terminada-postor',
    name: 'Offer Ended — Buyer Rejected',
    subject: '¡Oferta terminada!',
    desc: 'Notifies the seller that the top bidder (C.U.U) rejected their counteroffer and the offer closed.',
    category: 'En vivo',
    stage: 'Cierre',
    sections: [
      S('title', { eyebrow: '', text: '¡Oferta terminada!' }),
      SP('24'),
      S('text', { text: '¡El **{{C.U.U}}** rechazó la propuesta del **{{Vendedor}}** en la oferta **{{Toyota Yaris 2018}}**!' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-iniciada',
    name: 'Negotiation Started Notification',
    subject: '¡Negociación iniciada con éxito!',
    desc: 'Confirms the bidder started a negotiation with the seller and shows the proposal + guarantee.',
    category: 'Negociable',
    stage: 'Inicio',
    sections: [
      S('title', { eyebrow: '', text: '¡Negociación iniciada con éxito!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}}, Has iniciado una negociación con __{{Vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__. Con una propuesta de **US$ {{XX,XXX}}**. Ahora solo debes esperar la respuesta del vendedor.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('20'),
      S('quote', {
        proposalLabel: 'Tu propuesta:', proposalValue: 'US$ 10,000', expiresLabel: 'Vence', expiresValue: '23/01 15:00',
        guaranteeLabel: 'En garantía:', guaranteeValue: 'VM¢ 50',
      }),
      SP('20'),
      S('text', { text: '¿Aún te quedan dudas? __¡Subastin te ayuda a resolverlas!__', align: 'center' }),
      SP('14'),
      S('cta', { text: '¡Aprende a negociar con Subastin!', url: 'https://ayuda.vmcsubastas.com/es/collections/3079940-centro-de-ayuda-comprador', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'nueva-negociacion-vendedor',
    name: 'New Negotiation Started — Seller',
    subject: '¡Nueva negociación iniciada!',
    desc: 'Notifies the seller a buyer started a new negotiation with a proposal, the expectation gap, and prompts a response.',
    category: 'Negociable',
    stage: 'Inicio',
    sections: [
      S('title', { eyebrow: '', text: '¡Nueva negociación iniciada!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Tienes una nueva negociación en __{{oferta.Ejem: Toyota Hilux 2018}}__, con una propuesta de **US$ {{XX,XXX}}** enviada por __{{CUU.Ejem: B4GUSI}}__.' }),
      SP('20'),
      S('quote', {
        proposalLabel: 'Propuesta:', proposalValue: 'US$ 10,000', expiresLabel: 'Vence', expiresValue: '23/01 15:00',
        guaranteeLabel: 'Tu expectativa:', guaranteeValue: 'US$ 20,000',
        pctLabel: 'De tu expectativa:', pctValue: '50.00%',
      }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('text', { text: '__Acepta, rechaza o haz una contrapropuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Envía tu respuesta lo antes posible al participante en un máximo de __24 horas__ __aquí__.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-negociable',
    name: 'Negotiable Counteroffer Notification',
    subject: '¡Recibiste una contrapropuesta en {{Toyota Hilux 2018}}!',
    desc: 'Notifies the bidder of a seller counteroffer on a negotiable listing, with round comparison and deadline.',
    category: 'Negociable',
    stage: 'Negociación',
    sections: [
      S('title', { eyebrow: '', text: '¡Recibiste una contrapropuesta en {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Recibiste una contrapropuesta de **US$ {{XX,XXX}}** en __{{oferta.Ejem: Toyota Hilux 2018}}__ por __{{Vendedor}}__ válida hasta **{{Fecha y hora. d/m/Y - hh:mm}}**. Acepta, rechaza o haz una contrapropuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('negotiation', {
        round: '1°', roundLabel: 'Ronda de negociación.',
        yourLabel: 'Tu propuesta:', yourValue: 'US$ 10,000',
        sellerLabel: 'Vendedor propone:', sellerValue: 'US$ 19,000',
        expiresLabel: 'Vence', expiresValue: '23/01 17:00',
      }),
      SP('20'),
      S('text', { text: '__Acepta, rechaza o haz una contrapropuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Solo tienes un máximo de __5 rondas__ por negociación.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-hecha',
    name: 'Counteroffer Made — Buyer',
    subject: '¡Hiciste una contrapropuesta en {{Toyota Hilux 2018}}!',
    desc: 'Confirms the buyer made a counteroffer and is waiting for the seller response within the round deadline.',
    category: 'Negociable',
    stage: 'Negociación',
    sections: [
      S('title', { eyebrow: '', text: '¡Hiciste una contrapropuesta en {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Hiciste una contrapropuesta de **US$ {{XX,XXX}}** en __{{oferta.Ejem: Toyota Hilux 2018}}__. Ahora solo debes esperar la respuesta de __{{CUU.Ejem: B4GUSI}}__ a más tardar el **{{Fecha y hora. d/m/Y - hh:mm}}**.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('negotiation', {
        round: '1°', roundLabel: 'Ronda de negociación.',
        yourLabel: 'Propuesta:', yourValue: 'US$ 10,000',
        sellerLabel: 'Tu propuesta:', sellerValue: 'US$ 19,000',
        expiresLabel: 'Vence', expiresValue: '23/01 17:00',
      }),
      SP('20'),
      S('text', { text: '**Recuerda:** Solo tienes un máximo de __5 rondas__ por negociación.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-expirara-ultima-notificacion',
    name: 'Proposal Expiring — Last Notice',
    subject: '¡Última notificación! ¡La propuesta expirará!',
    desc: 'Final reminder that a negotiable proposal is about to expire, with the deadline penalty if no response is sent.',
    category: 'Negociable',
    stage: 'Alertas',
    sections: [
      S('title', { eyebrow: '', text: '¡Última notificación! ¡La propuesta expirará!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Última oportunidad!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Que la negociación se dará por concluida si es que una respuesta no es enviada antes de las __{{hh:mm}}__.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-expirara-hhmm',
    name: 'Proposal Expiring — Reminder',
    subject: '¡Propuesta expirará {{hh:mm}}!',
    desc: 'Reminds the recipient a negotiable proposal is waiting and will expire, prompting a response.',
    category: 'Negociable',
    stage: 'Alertas',
    sections: [
      S('title', { eyebrow: '', text: '¡Propuesta expirará {{hh:mm}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Acción requerida! ¡Tienes una propuesta esperando!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-por-expirar-muy-importante',
    name: 'Proposal Expiring — Urgent',
    subject: '¡Muy importante! ¡Propuesta por expirar {{hh:mm}}!',
    desc: 'Urgent escalation that a negotiable proposal is about to expire, prompting an immediate response.',
    category: 'Negociable',
    stage: 'Alertas',
    sections: [
      S('title', { eyebrow: '', text: '¡Muy importante! ¡Propuesta por expirar {{hh:mm}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Acción requerida! ¡Tienes una propuesta esperando!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-finalizada',
    name: 'Negotiation Ended Notification',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Notifies the bidder the seller rejected their proposal, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Lamentablemente __{{vendedor}}__ rechazó tu propuesta en __{{oferta: Toyota Hilux 2018}}__ y la negociación ha sido finalizada. Al rechazar tu propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'ganaste-oferta-negociable',
    name: 'Won Offer Notification — Negotiable',
    subject: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms the seller accepted the proposal, shows the winning bid, and the commission/guarantee/debt breakdown to unlock the purchase.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaron** tu propuesta y ganaste la __{{oferta.Ejem: Toyota Hilux 2018}}__ de __{{vendedor}}__ con tu propuesta de **US$ {{XX,XXX}}**.' }),
      SP('20'),
      S('won-vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4', winLabel: 'Tu propuesta ganadora:', winValue: 'US$ XX,XXX' }),
      SP('20'),
      S('text', { text: '¡Cancela la comisión para seguir con el proceso de compra!', align: 'center' }),
      SP('14'),
      S('costs', { l1: 'Comisión:', v1: 'US$ 500', l2: 'En garantía:', v2: 'US$ 50', l3: 'Deuda:', v3: 'US$ 450' }),
      SP('20'),
      S('list', { title: 'Documentación solicitada:', i1: 'Documento N°1', i2: 'Documento N°2' }),
      SP('16'),
      S('text', { text: 'En breve te estaremos enviando el acceso a las instrucciones de compra.' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu __historial de participación__ para seguir el proceso.' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-expirada',
    name: 'Negotiation Expired Notification',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Notifies the bidder their proposal expired, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Tu propuesta __expiro__ **US$ {{XX,XXX}}** {{oferta: Toyota Hilux 2018}}. Esta negociación con __{{vendedor}}__ ha finalizado.' }),
      SP('12'),
      S('text', { text: 'Al expirar tu propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-rechazada-comprador',
    name: 'Counteroffer Rejected — Buyer',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Confirms the buyer rejected the seller counteroffer, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '__Rechazaste__ la propuesta de **US$ {{XX,XXX}}** en __{{oferta: Toyota Hilux 2018}}__ de __{{vendedor}}__ y la negociación ha sido finalizada.' }),
      SP('12'),
      S('text', { text: 'Al rechazar la propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-aceptada-comprador',
    name: 'Counteroffer Accepted — Buyer',
    subject: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms the buyer accepted the seller counteroffer and won the offer, with the winning bid and the commission/guarantee/debt breakdown to unlock the purchase.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaste** la propuesta de __{{vendedor}}__ y ganaste en __{{oferta.Ejem: Toyota Hilux 2018}}__ con la propuesta de **US$ {{XX,XXX}}**.' }),
      SP('20'),
      S('won-vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4', winLabel: 'Tu propuesta ganadora:', winValue: 'US$ XX,XXX' }),
      SP('20'),
      S('text', { text: '¡Cancela la comisión para seguir con el proceso de compra!', align: 'center' }),
      SP('14'),
      S('costs', { l1: 'Comisión:', v1: 'US$ 500', l2: 'En garantía:', v2: 'US$ 50', l3: 'Deuda:', v3: 'US$ 450' }),
      SP('20'),
      S('list', { title: 'Documentación solicitada:', i1: 'Documento N°1', i2: 'Documento N°2' }),
      SP('16'),
      S('text', { text: 'En breve te estaremos enviando el acceso a las instrucciones de compra.' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu __historial de participación__ para seguir el proceso.' }),
      SP('30'),
    ],
  },
  {
    id: 'vendedor-acepta-propuesta',
    name: 'Proposal Accepted — Seller Confirmation',
    subject: '¡Aceptaste la propuesta en {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms to the seller that they accepted the buyer proposal, showing the winning bid and how it compares to their expectation.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Aceptaste la propuesta en {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaste** la propuesta de **US$ {{XX,XXX}}** por __{{CUU.Ejem: B4GUSI}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__, el **{{Fecha y hora. d/m/Y - hh:mm}}**.' }),
      SP('20'),
      S('won-vehicle', {
        img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4',
        winLabel: 'Propuesta ganadora:', winValue: 'US$ XX,XXX',
        pctLabel: 'De expectativa:', pctValue: '81.35%',
      }),
      SP('30'),
    ],
  },
];

export const getEmail = (id: string) => EMAILS.find((e) => e.id === id);
