/* Catálogo de correos ya armados. Sumar uno = agregar un objeto a EMAILS.
   Cada correo respeta el layout y distancias del original; el estilo (glass,
   gradientes, coral) lo aplica el render de secciones según patrones.md. */

import { Section } from './email-templates';

export interface EmailTemplate {
  id: string;        // slug para la URL
  name: string;      // nombre visible
  subject: string;   // asunto del correo
  desc: string;      // descripción corta para la card
  category?: string; // agrupa la card en el catálogo (ej. "En vivo")
  stage?: string;     // paso dentro del flujo de la categoría (ej. "Negociación"), pinta el stepper
  leadsTo?: string[]; // ids de correos a los que puede derivar (dibuja las líneas del diagrama de flujo)
  sections: Section[];
}

const ICON = {
  calendar: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-calendar.png',
  search: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-search.png',
  eye: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-eye.png',
  cards: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-cards.png',
  bank: 'https://cdn.vmcsubastas.com/services/boletin/assets/icon-bank-building.png',
  phone: 'https://cdn.vmcsubastas.com/services/boletin/assets/phone-bcp.png',
};

// orden real del flujo de negocio por categoría — no depende del orden de inserción en EMAILS
export const STAGE_ORDER: Record<string, string[]> = {
  'En vivo': ['Inicio', 'Resultado', 'Negociación', 'Habilitación', 'Cierre'],
  'Negociable': ['Inicio', 'Negociación', 'Alertas', 'Resultado'],
  'Proceso Interno Mapfre': ['Invitación', 'Participación', 'Cierre', 'Resultado'],
};

// mismos gradientes que ya usan los CTA de email-templates.ts (G_PRIMARY / G_NEGOTIABLE),
// que a su vez vienen de concorde/components/OfferCard.tsx (barras live/negotiable)
export const CATEGORY_GRADIENT: Record<string, string> = {
  'En vivo': 'linear-gradient(135deg,#ed8936 0%,#8460e5 100%)',
  'Negociable': 'linear-gradient(125deg,#00aeb1 0%,#00aeb1 40%,#8460e5 100%)',
  'Adquisición de SubasCoins': 'linear-gradient(135deg,#8460e5 0%,#3b1782 100%)',
  'Recarga': 'linear-gradient(135deg,#3b82f6 0%,#1d4ed8 100%)',
  'Proceso Compra y Venta': 'linear-gradient(135deg,#f97316 0%,#dc2626 100%)',
  'Registro': 'linear-gradient(135deg,#22c55e 0%,#15803d 100%)',
  'Canje de Puntos': 'linear-gradient(135deg,#f59e0b 0%,#b45309 100%)',
  'Contraseña': 'linear-gradient(135deg,#64748b 0%,#334155 100%)',
  'Visita Agendada': 'linear-gradient(135deg,#6366f1 0%,#4338ca 100%)',
  'Devolución de Saldo': 'linear-gradient(135deg,#d946ef 0%,#a21caf 100%)',
  'Actualizar Correo': 'linear-gradient(135deg,#06b6d4 0%,#0e7490 100%)',
  'Inhabilitación de Usuario': 'linear-gradient(135deg,#7f1d1d 0%,#450a0a 100%)',
  'Baja de Cuenta': 'linear-gradient(135deg,#78716c 0%,#44403c 100%)',
  'Usuarios Internos': 'linear-gradient(135deg,#ec4899 0%,#9d174d 100%)',
  'Proceso Interno Mapfre': 'linear-gradient(135deg,#ef4444 0%,#991b1b 100%)',
};

export const CATEGORY_SOLID: Record<string, string> = {
  'En vivo': '#ed8936',
  'Negociable': '#00aeb1',
  'Adquisición de SubasCoins': '#8460e5',
  'Recarga': '#3b82f6',
  'Proceso Compra y Venta': '#dc2626',
  'Registro': '#22c55e',
  'Canje de Puntos': '#f59e0b',
  'Contraseña': '#64748b',
  'Visita Agendada': '#6366f1',
  'Devolución de Saldo': '#d946ef',
  'Actualizar Correo': '#06b6d4',
  'Inhabilitación de Usuario': '#7f1d1d',
  'Baja de Cuenta': '#78716c',
  'Usuarios Internos': '#ec4899',
  'Proceso Interno Mapfre': '#ef4444',
};

// demo del design system Concorde (mismo asset que usan OfferCard/Detalle/Sala en concorde/bloques);
// swap por fotos reales del vehículo/ofertas cuando estén disponibles en el CDN
const DEMO_CAR = 'https://concorde-v2-theta.vercel.app/demo/bronco.jpg';
const PLACEHOLDER = { car: DEMO_CAR, thumb: DEMO_CAR, offer: DEMO_CAR };

// helper local: no repetir id/type a mano
const S = (type: Section['type'], content: Record<string, string>): Section => ({
  id: `${type}-${Math.random().toString(36).slice(2, 7)}`, type, content,
});
const SP = (height: string) => S('spacer', { height });

export const EMAILS: EmailTemplate[] = [
  {
    id: 'fee-subascoins',
    name: 'Fee Notice — SubasCoins',
    subject: 'Información importante sobre tus adquisiciones de SubasCoins',
    desc: 'Announces the new gateway fee and the fee-free options (BCP / CUU).',
    sections: [
      // layout y distancias del correo original
      S('title', { eyebrow: '', text: 'Información importante sobre tus adquisiciones de SubasCoins' }),
      SP('30'),
      S('text', { text: 'Queremos contarte que hemos realizado una actualización en nuestros Términos y Condiciones relacionada con la adquisición de SubasCoins en plataforma.' }),
      SP('20'),
      S('panel', {
        title: 'A partir del **1 de Julio** del presente año',
        body: 'Las compras de SubasCoins realizadas a través de la plataforma utilizando tarjeta de Crédito o Débito podrán incluir un **Fee por uso de pasarela**, asociado al procesamiento de la transacción.',
        iconUrl: ICON.calendar, badge: '', imageUrl: '', imageW: '85', imageH: '57',
      }),
      SP('20'),
      S('features', {
        heading: '¿Qué debes tener en cuenta sobre este Fee?',
        i1: ICON.search, t1: 'El costo del fee equivale al [[3.9%]] del monto de tu adquisición de SubasCoins',
        i2: ICON.eye, t2: 'Se te mostrará de manera clara y desagregada antes de realizar el pago',
        i3: ICON.cards, t3: 'Si tu tarjeta es en soles, el tipo de cambio será determinado por tu proveedor',
      }),
      SP('20'),
      S('panel', {
        title: 'Opciones **SIN FEE** por uso de pasarela',
        body: 'Puedes realizar tu recarga de saldo en dólares a través de ventanilla, agente o app del banco BCP utilizando tu CUU. Esta operación carece del cobro de este Fee.',
        iconUrl: ICON.bank, badge: 'white', imageUrl: ICON.phone, imageW: '85', imageH: '57',
      }),
      SP('30'),
    ],
  },
  {
    id: 'listo-participar',
    name: 'Ready to Bid — Participation',
    subject: '¡Listo para participar en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Confirms participation: details (date, seller, consignment) + live-room reminder.',
    category: 'En vivo',
    stage: 'Inicio',
    leadsTo: ['mejor-postor', 'ganador-directo'],
    sections: [
      // {{...}} = merge tags (se reemplazan en tu plataforma); **...** = acento
      S('title', { eyebrow: '', text: '¡Listo para participar en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario .Ejem: Gabriel Bruno}}, datos de tu participación:' }),
      SP('14'),
      S('details', {
        l1: 'Fecha y hora:', v1: 'Miércoles, 11 de octubre - 2:00 p.m.',
        l2: 'Vendedor:', v2: 'Financiera Automotriz',
        l3: 'Consignación:', v3: '50 SubasCoins',
      }),
      SP('16'),
      S('divider', {}),
      SP('16'),
      S('note', {
        title: 'Recuerda:',
        body: 'Al consignar, eres responsable de asegurar tu conexión a sala "En Vivo" y de participar enviando, al menos, un bid válido durante el proceso, o serás sancionado.',
      }),
      SP('30'),
    ],
  },
  {
    id: 'oportunidad-compra',
    name: 'Purchase Opportunity — 2nd/3rd Place',
    subject: '¡Tienes oportunidad de compra en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies 2nd/3rd-place bidders of a purchase opportunity and explains eligibility conditions.',
    category: 'En vivo',
    stage: 'Resultado',
    leadsTo: ['habilitado-comprar'],
    sections: [
      S('title', { eyebrow: '', text: '¡Tienes oportunidad de compra en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('14'),
      S('text', { text: '¡Felicidades estas entre los __3 mejores postores__! __Te notificaremos en caso se active tu oportunidad de compra.__' }),
      SP('16'),
      S('text', { text: '**Recuerda:** Tu garantía se mantendrá consignada hasta que el proceso de venta de la oferta haya finalizado. **¡Aún hay una oportunidad de ganar con VMC Subastas!**' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es la oportunidad de compra?**' }),
      SP('12'),
      S('text', { text: 'La oportunidad de compra es __una condición obtenida por el mejor postor__ en una oferta \'En Vivo\' con reserva y por el __2do o 3er lugar en un proceso sin reserva__.' }),
      SP('12'),
      S('text', { text: 'En caso de **activarse la oportunidad de compra** el participante adquirirá las __responsabilidades de ganador directo habilitado__ siendo responsable de seguir con el proceso de compra, bajo pena de sanción en caso de incumplimiento.' }),
      SP('30'),
    ],
  },
  {
    id: 'ganador-directo',
    name: 'Direct Winner — Purchase',
    subject: '¡Eres el Ganador Directo en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the direct winner, prompts to start the purchase, and states the sanctions.',
    category: 'En vivo',
    stage: 'Resultado',
    leadsTo: ['habilitado-comprar'],
    sections: [
      S('title', { eyebrow: '', text: '¡Eres el Ganador Directo en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario .Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! Estás a un paso de cumplir tus metas. __Inicia el proceso de compra__ ingresando a tu zona de usuario.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('text', { text: 'En cualquier caso, cuando el ganador directo habilitado haya **incumplido con alguna de sus responsabilidades**, será sancionado con la pérdida de 75 Puntos.' }),
      SP('12'),
      S('text', { text: 'VMC SUBASTAS también procederá a exigir el **pago equivalente a la comisión** establecido como contraprestación por el uso de la Billetera brindada, detrayéndola si fuese posible de la Billetera automáticamente; cuando el usuario carezca de fondos suficientes para cubrir el total de la comisión, se procederá a amortizar de manera parcial la deuda correspondiente detrayendo el íntegro de los fondos en Billetera del ganador, por lo que su usuario mantendrá una deuda en plataforma y su cuenta permanecerá restringida.' }),
      SP('30'),
    ],
  },
  {
    id: 'mejor-postor',
    name: 'Best Bidder Notification',
    subject: '¡Eres el Mejor Postor en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the current best bidder and explains what being top bidder means.',
    category: 'En vivo',
    stage: 'Resultado',
    leadsTo: ['contrapropuesta', 'opcion-compra', 'habilitado-comprar', 'oferta-terminada'],
    sections: [
      S('title', { eyebrow: '', text: '¡Eres el Mejor Postor en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades, estás a un paso para cumplir tus metas! Te notificaremos cuando tengas la respuesta del vendedor y __tu garantía se mantendrá consignada__ hasta ese momento.' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué significa ser mejor postor?**' }),
      SP('12'),
      S('text', { text: '__Mejor postor:__ Es quien realiza la mejor propuesta en una oferta "En Vivo" con Precio reserva, por lo cual su propuesta pasa a evaluación con el vendedor y este tendrá hasta **10 días hábiles** dar una respuesta a dicho ganador.' }),
      SP('30'),
    ],
  },
  {
    id: 'opcion-compra',
    name: 'Purchase Option Notification',
    subject: '¡Tienes opción de compra en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the buyer the seller granted a purchase option and prompts them to accept it.',
    category: 'En vivo',
    stage: 'Resultado',
    leadsTo: ['habilitado-comprar'],
    sections: [
      S('title', { eyebrow: '', text: '¡Tienes opción de compra en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades el vendedor te dio la **opción de compra**! Ingresa a tu zona de usuario para **aceptarla**.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es la opción de compra?**' }),
      SP('12'),
      S('text', { text: 'La opción de compra es una __condicional que todo vendedor podrá activar__ cuando crea conveniente.' }),
      SP('12'),
      S('text', { text: 'El participante, a quien se le dé la opción de compra y acepte la misma asumirá todas las __responsabilidades de un ganador directo habilitado__.' }),
      SP('12'),
      S('text', { text: 'El participante podrá rechazar dicha opción, libre de sanciones asociadas.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta',
    name: 'Counteroffer Notification',
    subject: '¡Recibiste una contrapropuesta en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the top bidder of a seller counteroffer and explains the counteroffer mechanic.',
    category: 'En vivo',
    stage: 'Negociación',
    leadsTo: ['propuesta-rechazada', 'habilitado-comprar'],
    sections: [
      S('title', { eyebrow: '', text: '¡Recibiste una contrapropuesta en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu zona de usuario y **revisa la contrapropuesta del vendedor**!' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**¿Qué es una contrapropuesta?**' }),
      SP('12'),
      S('text', { text: 'El vendedor se reserva el derecho de declinar la propuesta del mejor postor y **optar por hacerle una contrapropuesta sobre el monto ofrecido**.' }),
      SP('12'),
      S('text', { text: 'En caso aceptes la contrapropuesta asumirás las **responsabilidades del ganador directo habilitado**.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-rechazada',
    name: 'Rejected Proposal Notification',
    subject: '¡Rechazaste la propuesta en la oferta {{Toyota Yaris 2018}}!',
    desc: 'Confirms the bidder rejected the seller counteroffer and their consignment was released.',
    category: 'En vivo',
    stage: 'Negociación',
    leadsTo: ['oferta-terminada-postor'],
    sections: [
      S('title', { eyebrow: '', text: '¡Rechazaste la propuesta en la oferta {{Toyota Yaris 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Has rechazado la propuesta de __{{vendedor}}__ en la oferta **{{Toyota Yaris 2018}}**. Ahora te encuentras fuera del proceso de compra.' }),
      SP('16'),
      S('text', { text: '**Tu consignación fue liberada a tu billetera.**' }),
      SP('30'),
    ],
  },
  {
    id: 'habilitado-comprar',
    name: 'Enabled to Buy Notification',
    subject: '¡Has sido habilitado en la oferta {{Toyota Hilux 2018}}!',
    desc: 'Notifies the participant they are enabled to buy, prompts the purchase flow, and states the sanctions.',
    category: 'En vivo',
    stage: 'Habilitación',
    sections: [
      S('title', { eyebrow: '', text: '¡Has sido habilitado en la oferta {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades estás **habilitado para comprar**! __Inicia el proceso de compra__ ingresando a tu zona de usuario.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('text', { text: 'En cualquier caso, cuando el ganador directo habilitado haya **incumplido con alguna de sus responsabilidades**, será sancionado con la pérdida de 75 Puntos.' }),
      SP('12'),
      S('text', { text: 'VMC SUBASTAS también procederá a exigir el **pago equivalente a la comisión** establecida como contraprestación por el uso del servicio brindado, detrayéndola si fuese posible de su Billetera automáticamente; cuando el usuario carezca de fondos suficientes para cubrir el total de la comisión, se procederá a amortizar de manera parcial la deuda correspondiente detrayendo el íntegro de los fondos en Billetera del ganador, por lo que el usuario mantendrá una deuda en plataforma y su cuenta permanecerá restringida.' }),
      SP('30'),
    ],
  },
  {
    id: 'oferta-terminada',
    name: 'Offer Ended Notification',
    subject: '¡Oferta terminada!',
    desc: 'Notifies bidders the seller rejected the top proposal and the offer closed.',
    category: 'En vivo',
    stage: 'Cierre',
    sections: [
      S('title', { eyebrow: '', text: '¡Oferta terminada!' }),
      SP('24'),
      S('text', { text: '¡El **{{Vendedor}}** rechazó la propuesta del **{{C.U.U}}** en la oferta **{{Toyota Yaris 2018}}**!' }),
      SP('30'),
    ],
  },
  {
    id: 'oferta-terminada-postor',
    name: 'Offer Ended — Buyer Rejected',
    subject: '¡Oferta terminada!',
    desc: 'Notifies the seller that the top bidder (C.U.U) rejected their counteroffer and the offer closed.',
    category: 'En vivo',
    stage: 'Cierre',
    sections: [
      S('title', { eyebrow: '', text: '¡Oferta terminada!' }),
      SP('24'),
      S('text', { text: '¡El **{{C.U.U}}** rechazó la propuesta del **{{Vendedor}}** en la oferta **{{Toyota Yaris 2018}}**!' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-iniciada',
    name: 'Negotiation Started Notification',
    subject: '¡Negociación iniciada con éxito!',
    desc: 'Confirms the bidder started a negotiation with the seller and shows the proposal + guarantee.',
    category: 'Negociable',
    stage: 'Inicio',
    leadsTo: ['contrapropuesta-negociable', 'ganaste-oferta-negociable', 'negociacion-finalizada', 'propuesta-expirara-hhmm'],
    sections: [
      S('title', { eyebrow: '', text: '¡Negociación iniciada con éxito!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}}, Has iniciado una negociación con __{{Vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__. Con una propuesta de **US$ {{XX,XXX}}**. Ahora solo debes esperar la respuesta del vendedor.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('20'),
      S('quote', {
        proposalLabel: 'Tu propuesta:', proposalValue: 'US$ 10,000', expiresLabel: 'Vence', expiresValue: '23/01 15:00',
        guaranteeLabel: 'En garantía:', guaranteeValue: 'VM¢ 50',
      }),
      SP('20'),
      S('text', { text: '¿Aún te quedan dudas? __¡Subastin te ayuda a resolverlas!__', align: 'center' }),
      SP('14'),
      S('cta', { text: '¡Aprende a negociar con Subastin!', url: 'https://ayuda.vmcsubastas.com/es/collections/3079940-centro-de-ayuda-comprador', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'nueva-negociacion-vendedor',
    name: 'New Negotiation Started — Seller',
    subject: '¡Nueva negociación iniciada!',
    desc: 'Notifies the seller a buyer started a new negotiation with a proposal, the expectation gap, and prompts a response.',
    category: 'Negociable',
    stage: 'Inicio',
    leadsTo: ['contrapropuesta-negociable', 'vendedor-acepta-propuesta', 'negociacion-finalizada', 'propuesta-expirara-hhmm'],
    sections: [
      S('title', { eyebrow: '', text: '¡Nueva negociación iniciada!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Tienes una nueva negociación en __{{oferta.Ejem: Toyota Hilux 2018}}__, con una propuesta de **US$ {{XX,XXX}}** enviada por __{{CUU.Ejem: B4GUSI}}__.' }),
      SP('20'),
      S('quote', {
        proposalLabel: 'Propuesta:', proposalValue: 'US$ 10,000', expiresLabel: 'Vence', expiresValue: '23/01 15:00',
        guaranteeLabel: 'Tu expectativa:', guaranteeValue: 'US$ 20,000',
        pctLabel: 'De tu expectativa:', pctValue: '50.00%',
      }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('text', { text: '__Acepta, rechaza o haz una contrapropuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Envía tu respuesta lo antes posible al participante en un máximo de __24 horas__ __aquí__.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-negociable',
    name: 'Negotiable Counteroffer Notification',
    subject: '¡Recibiste una contrapropuesta en {{Toyota Hilux 2018}}!',
    desc: 'Notifies the bidder of a seller counteroffer on a negotiable listing, with round comparison and deadline.',
    category: 'Negociable',
    stage: 'Negociación',
    leadsTo: ['contrapropuesta-hecha', 'contrapropuesta-aceptada-comprador', 'contrapropuesta-rechazada-comprador'],
    sections: [
      S('title', { eyebrow: '', text: '¡Recibiste una contrapropuesta en {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Recibiste una contrapropuesta de **US$ {{XX,XXX}}** en __{{oferta.Ejem: Toyota Hilux 2018}}__ por __{{Vendedor}}__ válida hasta **{{Fecha y hora. d/m/Y - hh:mm}}**. Acepta, rechaza o haz una contrapropuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('negotiation', {
        round: '1°', roundLabel: 'Ronda de negociación.',
        yourLabel: 'Tu propuesta:', yourValue: 'US$ 10,000',
        sellerLabel: 'Vendedor propone:', sellerValue: 'US$ 19,000',
        expiresLabel: 'Vence', expiresValue: '23/01 17:00',
      }),
      SP('20'),
      S('text', { text: '__Acepta, rechaza o haz una contrapropuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Solo tienes un máximo de __5 rondas__ por negociación.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-hecha',
    name: 'Counteroffer Made — Buyer',
    subject: '¡Hiciste una contrapropuesta en {{Toyota Hilux 2018}}!',
    desc: 'Confirms the buyer made a counteroffer and is waiting for the seller response within the round deadline.',
    category: 'Negociable',
    stage: 'Negociación',
    leadsTo: ['negociacion-finalizada', 'ganaste-oferta-negociable', 'contrapropuesta-negociable', 'propuesta-expirara-hhmm'],
    sections: [
      S('title', { eyebrow: '', text: '¡Hiciste una contrapropuesta en {{Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Hiciste una contrapropuesta de **US$ {{XX,XXX}}** en __{{oferta.Ejem: Toyota Hilux 2018}}__. Ahora solo debes esperar la respuesta de __{{CUU.Ejem: B4GUSI}}__ a más tardar el **{{Fecha y hora. d/m/Y - hh:mm}}**.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: 'Río Magdalena', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb }),
      SP('20'),
      S('negotiation', {
        round: '1°', roundLabel: 'Ronda de negociación.',
        yourLabel: 'Propuesta:', yourValue: 'US$ 10,000',
        sellerLabel: 'Tu propuesta:', sellerValue: 'US$ 19,000',
        expiresLabel: 'Vence', expiresValue: '23/01 17:00',
      }),
      SP('20'),
      S('text', { text: '**Recuerda:** Solo tienes un máximo de __5 rondas__ por negociación.' }),
      SP('12'),
      S('text', { text: 'Más información sobre la oferta negociable __aquí__.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-expirara-ultima-notificacion',
    name: 'Proposal Expiring — Last Notice',
    subject: '¡Última notificación! ¡La propuesta expirará!',
    desc: 'Final reminder that a negotiable proposal is about to expire, with the deadline penalty if no response is sent.',
    category: 'Negociable',
    stage: 'Alertas',
    leadsTo: ['negociacion-expirada'],
    sections: [
      S('title', { eyebrow: '', text: '¡Última notificación! ¡La propuesta expirará!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Última oportunidad!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('24'),
      S('text', { text: '**Recuerda:** Que la negociación se dará por concluida si es que una respuesta no es enviada antes de las __{{hh:mm}}__.' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-expirara-hhmm',
    name: 'Proposal Expiring — Reminder',
    subject: '¡Propuesta expirará {{hh:mm}}!',
    desc: 'Reminds the recipient a negotiable proposal is waiting and will expire, prompting a response.',
    category: 'Negociable',
    stage: 'Alertas',
    leadsTo: ['propuesta-expirara-ultima-notificacion'],
    sections: [
      S('title', { eyebrow: '', text: '¡Propuesta expirará {{hh:mm}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Acción requerida! ¡Tienes una propuesta esperando!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'propuesta-por-expirar-muy-importante',
    name: 'Proposal Expiring — Urgent',
    subject: '¡Muy importante! ¡Propuesta por expirar {{hh:mm}}!',
    desc: 'Urgent escalation that a negotiable proposal is about to expire, prompting an immediate response.',
    category: 'Negociable',
    stage: 'Alertas',
    leadsTo: ['negociacion-expirada'],
    sections: [
      S('title', { eyebrow: '', text: '¡Muy importante! ¡Propuesta por expirar {{hh:mm}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Grabriel Bruno / Vendedor}},' }),
      SP('10'),
      S('text', { text: 'La propuesta de **{{US$ XX,XX}}** enviada por __{{B4GUSI / vendedor}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__ expira a las **{{hh:mm}}**. Envía tu respuesta lo antes posible __aquí__.' }),
      SP('20'),
      S('vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', caption: '', thumb1: PLACEHOLDER.thumb, thumb2: PLACEHOLDER.thumb, thumb3: PLACEHOLDER.thumb }),
      SP('16'),
      S('text', { text: '**¡Acción requerida! ¡Tienes una propuesta esperando!**', align: 'center' }),
      SP('4'),
      S('text', { text: '__Envía tu respuesta:__', align: 'center' }),
      SP('12'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona', variant: 'negotiable' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-finalizada',
    name: 'Negotiation Ended Notification',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Notifies the bidder the seller rejected their proposal, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Lamentablemente __{{vendedor}}__ rechazó tu propuesta en __{{oferta: Toyota Hilux 2018}}__ y la negociación ha sido finalizada. Al rechazar tu propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'ganaste-oferta-negociable',
    name: 'Won Offer Notification — Negotiable',
    subject: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms the seller accepted the proposal, shows the winning bid, and the commission/guarantee/debt breakdown to unlock the purchase.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaron** tu propuesta y ganaste la __{{oferta.Ejem: Toyota Hilux 2018}}__ de __{{vendedor}}__ con tu propuesta de **US$ {{XX,XXX}}**.' }),
      SP('20'),
      S('won-vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4', winLabel: 'Tu propuesta ganadora:', winValue: 'US$ XX,XXX' }),
      SP('20'),
      S('text', { text: '¡Cancela la comisión para seguir con el proceso de compra!', align: 'center' }),
      SP('14'),
      S('costs', { l1: 'Comisión:', v1: 'US$ 500', l2: 'En garantía:', v2: 'US$ 50', l3: 'Deuda:', v3: 'US$ 450' }),
      SP('20'),
      S('list', { title: 'Documentación solicitada:', i1: 'Documento N°1', i2: 'Documento N°2' }),
      SP('16'),
      S('text', { text: 'En breve te estaremos enviando el acceso a las instrucciones de compra.' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu __historial de participación__ para seguir el proceso.' }),
      SP('30'),
    ],
  },
  {
    id: 'negociacion-expirada',
    name: 'Negotiation Expired Notification',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Notifies the bidder their proposal expired, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: 'Tu propuesta __expiro__ **US$ {{XX,XXX}}** {{oferta: Toyota Hilux 2018}}. Esta negociación con __{{vendedor}}__ ha finalizado.' }),
      SP('12'),
      S('text', { text: 'Al expirar tu propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-rechazada-comprador',
    name: 'Counteroffer Rejected — Buyer',
    subject: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}',
    desc: 'Confirms the buyer rejected the seller counteroffer, the negotiation ended, and the guarantee was released.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Negociación finalizada {{oferta: Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '__Rechazaste__ la propuesta de **US$ {{XX,XXX}}** en __{{oferta: Toyota Hilux 2018}}__ de __{{vendedor}}__ y la negociación ha sido finalizada.' }),
      SP('12'),
      S('text', { text: 'Al rechazar la propuesta, **tu garantía ha sido liberada a tu billetera.**' }),
      SP('20'),
      S('amount', { label: 'Garantía liberada:', value: 'US$ 50' }),
      SP('24'),
      S('offers', {
        heading: '¡Tenemos más oportunidades negociables!',
        sub: 'Estas son algunas ofertas especiales para ti:',
        c1img: PLACEHOLDER.offer, c1name: 'Honda Pilot', c1year: '2017',
        c2img: PLACEHOLDER.offer, c2name: 'Honda Pilot', c2year: '2017',
        c3img: PLACEHOLDER.offer, c3name: 'Honda Pilot', c3year: '2017',
        c4img: PLACEHOLDER.offer, c4name: 'Honda Pilot', c4year: '2017',
      }),
      SP('30'),
    ],
  },
  {
    id: 'contrapropuesta-aceptada-comprador',
    name: 'Counteroffer Accepted — Buyer',
    subject: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms the buyer accepted the seller counteroffer and won the offer, with the winning bid and the commission/guarantee/debt breakdown to unlock the purchase.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Has ganado {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaste** la propuesta de __{{vendedor}}__ y ganaste en __{{oferta.Ejem: Toyota Hilux 2018}}__ con la propuesta de **US$ {{XX,XXX}}**.' }),
      SP('20'),
      S('won-vehicle', { img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4', winLabel: 'Tu propuesta ganadora:', winValue: 'US$ XX,XXX' }),
      SP('20'),
      S('text', { text: '¡Cancela la comisión para seguir con el proceso de compra!', align: 'center' }),
      SP('14'),
      S('costs', { l1: 'Comisión:', v1: 'US$ 500', l2: 'En garantía:', v2: 'US$ 50', l3: 'Deuda:', v3: 'US$ 450' }),
      SP('20'),
      S('list', { title: 'Documentación solicitada:', i1: 'Documento N°1', i2: 'Documento N°2' }),
      SP('16'),
      S('text', { text: 'En breve te estaremos enviando el acceso a las instrucciones de compra.' }),
      SP('10'),
      S('text', { text: 'Ingresa a tu __historial de participación__ para seguir el proceso.' }),
      SP('30'),
    ],
  },
  {
    id: 'vendedor-acepta-propuesta',
    name: 'Proposal Accepted — Seller Confirmation',
    subject: '¡Aceptaste la propuesta en {{oferta.Ejem: Toyota Hilux 2018}}!',
    desc: 'Confirms to the seller that they accepted the buyer proposal, showing the winning bid and how it compares to their expectation.',
    category: 'Negociable',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: '¡Aceptaste la propuesta en {{oferta.Ejem: Toyota Hilux 2018}}!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('10'),
      S('text', { text: '¡Felicidades! **aceptaste** la propuesta de **US$ {{XX,XXX}}** por __{{CUU.Ejem: B4GUSI}}__ en __{{oferta.Ejem: Toyota Hilux 2018}}__, el **{{Fecha y hora. d/m/Y - hh:mm}}**.' }),
      SP('20'),
      S('won-vehicle', {
        img: PLACEHOLDER.car, tag: 'Toyota Hilux 2018', statLabel: 'Propuestas', statValue: '4',
        winLabel: 'Propuesta ganadora:', winValue: 'US$ XX,XXX',
        pctLabel: 'De expectativa:', pctValue: '81.35%',
      }),
      SP('30'),
    ],
  },
  {
    id: 'adquisicion-subascoins-exitosa',
    name: 'SubasCoins Purchase — Success',
    subject: '¡Adquisición de SubasCoins exitosa!',
    desc: 'Confirms a successful SubasCoins purchase with the order summary (card, amount, date) and the final-sale notice.',
    category: 'Adquisición de SubasCoins',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: '¡Adquisición de SubasCoins exitosa!' }),
      SP('24'),
      S('success', { title: '¡Adquiriste', value: '>S< {{XX}}', caption: 'SubasCoins con éxito' }),
      SP('24'),
      S('text', { text: '**Resumen de transacción:**' }),
      SP('10'),
      S('details', {
        l1: 'Número de pedido:', v1: '{{Nº de pedido.Ejem: 3361071000}}',
        l2: 'Tarjetahabiente:', v2: '{{Nombre en tarjeta.Ejem: Justo Subastin}}',
        l3: 'Tarjeta:', v3: '{{Tarjeta.Ejem: 4444 **** **** 1235 VISA}}',
      }),
      SP('4'),
      S('details', {
        l1: 'Fecha y hora:', v1: '{{Fecha y hora. d/m/Y hh:mm:ss}}',
        l2: 'Importe:', v2: 'US$ {{XX}}',
        l3: 'Moneda:', v3: 'Dólares americanos',
      }),
      SP('4'),
      S('details', { l1: 'Descripción:', v1: 'Adquisición de SubasCoins', l2: '', v2: '', l3: '', v3: '' }),
      SP('20'),
      S('note', {
        title: 'Importante:',
        body: 'Toda adquisición de SubasCoins es final y definitiva. Los SubasCoins jamás podrán ser reembolsados. Recuerda que podrás usar tus SubasCoins para consignar y cubrir comisiones.',
      }),
      SP('20'),
      S('text', { text: 'Si desconoces esta actividad, por favor contáctanos inmediatamente a __https://ayuda.vmcsubastas.com/es/__' }),
      SP('16'),
      S('text', { text: 'Equipo VMC Subastas.' }),
      SP('4'),
      S('text', { text: 'Este es un mensaje automático, por favor evita responder este mail.' }),
      SP('30'),
    ],
  },
  {
    id: 'recarga-exitosa',
    name: 'Wallet Top-up — Success',
    subject: '¡Recarga exitosa!',
    desc: 'Confirms a successful wallet top-up (recharge) with the recharged amount.',
    category: 'Recarga',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: '¡Recarga exitosa!' }),
      SP('24'),
      S('success', { title: '¡Recargaste', value: 'US$ {{XX}}', caption: 'Dólares con éxito!' }),
      SP('24'),
      S('text', { text: 'Equipo VMC Subastas.' }),
      SP('4'),
      S('text', { text: 'Este es un mensaje automático, por favor evita responder este mail.' }),
      SP('30'),
    ],
  },
  {
    id: 'completa-proceso-compra',
    name: 'Purchase Completion — Urgent Reminder',
    subject: '¡Muy urgente! Acción requerida en la oferta: {{Toyota Hilux 2018}}.',
    desc: 'Urgent reminder to the enabled winner to complete the purchase process before the deadline, with the same sanctions as the enablement notice.',
    category: 'Proceso Compra y Venta',
    stage: 'Recordatorio',
    sections: [
      S('title', { eyebrow: '', text: '¡Muy urgente! Acción requerida en la oferta: {{Toyota Hilux 2018}}.' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('14'),
      S('text', { text: '__¡Te queda poco tiempo!__ __Completa proceso de compra ingresando a tu zona de usuario hasta__ **30/07/21 - 8:00 p.m!**' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('text', { text: 'En cualquier caso, cuando el ganador directo habilitado haya **incumplido con alguna de sus responsabilidades**, será sancionado con la pérdida de 75 Puntos.' }),
      SP('12'),
      S('text', { text: 'VMC SUBASTAS también procederá a exigir el **pago equivalente a la comisión** establecida como contraprestación por el uso del servicio brindado, detrayéndola si fuese posible de su Billetera automáticamente; cuando el usuario carezca de fondos suficientes para cubrir el total de la comisión, se procederá a amortizar de manera parcial la deuda correspondiente detrayendo el íntegro de los fondos en Billetera del ganador, por lo que el usuario mantendrá una deuda en plataforma y su cuenta permanecerá restringida.' }),
      SP('30'),
    ],
  },
  {
    id: 'bienvenida-registro',
    name: 'Welcome — Registration Confirmed',
    subject: '¡Bienvenido Cazador de ofertas!',
    desc: 'Welcomes the new user, shows their C.U.U. and registered data, and explains the two account-activation paths (SubasCoins vs. bank recharge).',
    category: 'Registro',
    stage: 'Bienvenida',
    sections: [
      S('title', { eyebrow: '', text: '¡Bienvenido Cazador de ofertas!' }),
      SP('24'),
      S('text', { text: '¡{{Nombre usuario.Ejem: Gabriel Bruno}}, queremos informarte que ya estás registrado!' }),
      SP('14'),
      S('text', { text: 'Este es tu Código Único de Usuario: **{{C.U.U.Ejem: ZOOY6U}}**' }),
      SP('14'),
      S('text', { text: 'Tu Código Único de Usuario __(C.U.U)__ te servirá en todos los procesos relacionados a participaciones, compras en nuestro Marketplace y también para proteger tu identidad.' }),
      SP('20'),
      S('text', { text: '**Estos son tus datos registrados:**' }),
      SP('8'),
      S('list', {
        i1: 'Correo: {{email.Ejem: subastin@tucorreo.com}}',
        i2: 'Celular: {{celular.Ejem: 987159725}}',
        i3: 'DNI: {{dni.Ejem: 23581321}}',
      }),
      SP('20'),
      S('divider', {}),
      SP('20'),
      S('text', { text: '__¡Ahora solo debes activar tu cuenta!__', align: 'center' }),
      SP('16'),
      S('icon-text', { icon: '🪙', title: '', text: 'Activa tu cuenta **adquiriendo SubasCoins** o mediante recarga y participa de esa oferta que tanto te interesa.' }),
      SP('16'),
      S('text', { text: '__Activación rápida con SubasCoins aquí:__', align: 'center' }),
      SP('10'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('20'),
      S('text', { text: 'Al activar tu cuenta con **SubasCoins** participas de una manera práctica y eficiente en las ofertas de tu interés.' }),
      SP('20'),
      S('divider', {}),
      SP('20'),
      S('icon-text', { icon: '🏦', title: 'Activación alternativa mediante recarga:', text: '• Hasta 24 horas para ser validada.\n• Menor capacidad de participación.' }),
      SP('16'),
      S('amount', { label: 'Código Único de Usuario:', value: '{{C.U.U.Ejem: ZOOY6U}}' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('columns', {
        h1: 'En línea', h2: 'En ventanilla',
        body1: 'Ingresa a **VíaBCP.com** para realizar la transferencia electrónica. Haz clic en **Pagos y servicios**, selecciona **Empresas diversas** y busca **VMC Subastas**. En **Servicios**, selecciona **Recarga** y una vez seleccionado, se te solicitará tu Código Único de Usuario y el monto que deseas recargar.',
        body2: 'Acércate a una agencia BCP. Indícale al cajero en ventanilla que quieres hacer un depósito a la Cuenta recaudadora de VMC SUBASTAS servicio de recarga. Luego se te solicitará tu Código Único de Usuario y el monto que deseas recargar.',
      }),
      SP('30'),
    ],
  },
  {
    id: 'canje-puntos-exitoso',
    name: 'Points Redemption — Success',
    subject: '¡Canje de Puntos VMC exitoso!',
    desc: 'Confirms a successful SubasCoins-to-VMC-Points redemption, the new user risk category, and the final-sale notice.',
    category: 'Canje de Puntos',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: '¡Canje de Puntos VMC exitoso!' }),
      SP('24'),
      S('success', { title: '{{Nombre usuario.Ejem: Gabriel Bruno}}, canjeaste', value: '30', caption: 'Puntos VMC con éxito!' }),
      SP('8'),
      S('text', { text: 'Tu nueva categoría de riesgo de usuario es: **{{Categoría.Ejem: Regular}}** ⭐ {{Puntos.Ejem: 15}}', align: 'center' }),
      SP('24'),
      S('text', { text: '**Resumen de transacción:**' }),
      SP('10'),
      S('details', {
        l1: 'Fecha y hora:', v1: '{{Fecha y hora. d/m/Y hh:mm:ss}}',
        l2: 'Importe:', v2: '>S< {{XX}} SubasCoins',
        l3: 'Concepto:', v3: 'Canje de Puntos VMC',
      }),
      SP('20'),
      S('note', {
        title: 'Importante:',
        body: 'Canjear SubasCoins por Puntos VMC es una operación final y definitiva.',
      }),
      SP('20'),
      S('text', { text: 'Equipo VMC Subastas.' }),
      SP('4'),
      S('text', { text: 'Este es un mensaje automático, por favor evita responder este mail.' }),
      SP('30'),
    ],
  },
  {
    id: 'nueva-contrasena',
    name: 'Password Reset — Link',
    subject: 'Nueva contraseña',
    desc: 'Sends the user a password-reset link via button, with a plain-text fallback URL.',
    category: 'Contraseña',
    stage: 'Recuperación',
    sections: [
      S('title', { eyebrow: '', text: 'Nueva contraseña' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel}}, **cambia tu contraseña** haciendo click en el siguiente botón:', align: 'center' }),
      SP('20'),
      S('cta', { text: 'Nueva contraseña', url: 'https://vmcsubastas.com/es/activate12358132134demo' }),
      SP('24'),
      S('text', { text: 'También puedes copiar y pegar este enlace en tu navegador', align: 'center' }),
      SP('8'),
      S('text', { text: '__https://vmcsubastas.com/es/activate12358132134demo__', align: 'center' }),
      SP('24'),
      S('text', { text: 'Equipo VMC Subastas.' }),
      SP('4'),
      S('text', { text: 'Este es un mensaje automático, por favor evita responder este mail.' }),
      SP('30'),
    ],
  },
  {
    id: 'visita-agendada',
    name: 'Scheduled Visit — Confirmation',
    subject: 'Visita agendada en la oferta {{Toyota Hilux 2018}}',
    desc: 'Confirms a scheduled vehicle visit with location, address, reference and date/time, plus COVID-19 preventive measures.',
    category: 'Visita Agendada',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: 'Visita agendada en la oferta {{Toyota Hilux 2018}}' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario .Ejem: Gabriel Bruno}}, estos son los datos de tu visita:' }),
      SP('16'),
      S('details', {
        l1: 'Ubicación:', v1: '{{Ubicación.Ejem: SAN MARTIN DE PORRES}}',
        l2: 'Dirección:', v2: '{{Dirección.Ejem: Av. Tomás Valle 601.}}',
        l3: 'Referencia:', v3: '{{Referencia.Ejem: Cruce con panamericana Norte.}}',
      }),
      SP('4'),
      S('details', { l1: 'Fecha y hora:', v1: '**{{Fecha y hora.Ejem: Miércoles, 11 de agosto - 2:00 p.m.}}**', l2: '', v2: '', l3: '', v3: '' }),
      SP('20'),
      S('divider', {}),
      SP('16'),
      S('note', {
        title: 'Recuerda:',
        body: 'Llevar DNI, cubrebocas y protector facial como medidas preventivas ante el COVID-19.',
      }),
      SP('30'),
    ],
  },
  {
    id: 'devolucion-saldo-exitosa',
    name: 'Balance Refund — Success',
    subject: '¡Tu cuenta ha sido congelada!',
    desc: 'Confirms the account freeze and refund request were processed successfully, with the refunded amount and date.',
    category: 'Devolución de Saldo',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: '¡Tu cuenta ha sido congelada!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel}},' }),
      SP('14'),
      S('text', { text: 'Tu solicitud de devolución por **US$ {{XX,XXX}}** fue realizada correctamente el **{{Fecha y hora. d/m/Y - hh:mm}}**.' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('30'),
    ],
  },
  {
    id: 'devolucion-saldo-error',
    name: 'Balance Refund — Request Error',
    subject: '¡Hubo un problema con tu solicitud!',
    desc: 'Notifies the user their refund request was cancelled due to a data issue, lists what to verify, and prompts a resubmission.',
    category: 'Devolución de Saldo',
    stage: 'Error',
    sections: [
      S('title', { eyebrow: '', text: '¡Hubo un problema con tu solicitud!' }),
      SP('24'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel}},' }),
      SP('14'),
      S('text', { text: '__El proceso de solicitud de devolución ha sido cancelado.__' }),
      SP('20'),
      S('text', { text: '**Recuerda:**' }),
      SP('8'),
      S('list', {
        i1: 'Si solicitaste "devolución a terceros" debes tener la información en la sección correspondiente.',
        i2: 'Verifica que tu número de cuenta bancaria sea correcto.',
        i3: 'Usa una cuenta en dólares americanos.',
      }),
      SP('4'),
      S('list', { i1: 'Si solicitaste la anulación del proceso, se descontarán **US$ 30** por concepto de gastos administrativos.' }),
      SP('20'),
      S('text', { text: '**Por favor, verifica que la información sea correcta y presiona nuevamente con la solicitud de congelamiento de cuenta.**', align: 'center' }),
      SP('20'),
      S('cta', { text: 'VAMOS', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('30'),
    ],
  },
  {
    id: 'actualizar-correo',
    name: 'Email Update — Verification Link',
    subject: 'Nueva correo de contacto',
    desc: 'Sends a verification link to confirm a new contact email, with a plain-text fallback URL.',
    category: 'Actualizar Correo',
    stage: 'Verificación',
    sections: [
      S('title', { eyebrow: '', text: 'Nueva correo de contacto' }),
      SP('24'),
      S('text', { text: '{{Correo.Ejem: gfajardo@correo.com}}, **valida tu nuevo correo electrónico** haciendo click en el siguiente botón:', align: 'center' }),
      SP('20'),
      S('cta', { text: 'Valida', url: 'https://vmcsubastas.com/es/activate12358132134demo' }),
      SP('24'),
      S('text', { text: 'También puedes copiar y pegar este enlace en tu navegador', align: 'center' }),
      SP('8'),
      S('text', { text: '__https://vmcsubastas.com/es/activate12358132134demo__', align: 'center' }),
      SP('24'),
      S('text', { text: 'Equipo VMC Subastas.' }),
      SP('4'),
      S('text', { text: 'Este es un mensaje automático, por favor evita responder este mail.' }),
      SP('30'),
    ],
  },
  {
    id: 'inhabilitacion-suplantacion-identidad',
    name: 'Account Disabled — Identity Impersonation',
    subject: 'Inhabilitación de cuenta',
    desc: 'Notifies the user their account was permanently disabled for impersonating another person or entity, citing the fraud-prevention policy clause.',
    category: 'Inhabilitación de Usuario',
    stage: 'Suplantación de Identidad',
    sections: [
      S('title', { eyebrow: '', text: 'Inhabilitación de cuenta' }),
      SP('24'),
      S('text', { text: '__{{Nombre usuario.Ejem: Hugo Rafael}}__, te informamos que tu cuenta ha sido inhabilitada por incumplir con las Condiciones y Términos de uso de nuestro servicio, los mismos que declaraste haber leído y comprendido al registrarte y en cada inicio de sesión en Plataforma. Te recordamos que todo usuario reconoce y acepta que:' }),
      SP('20'),
      S('text', { text: '**Título VI. POLÍTICA DE PREVENCIÓN DE FRAUDE**', align: 'center' }),
      SP('4'),
      S('text', { text: '**2. Respecto al uso del servicio**', align: 'center' }),
      SP('20'),
      S('text', { text: 'Su cuenta será inhabilitada permanentemente de verificarse que ha suplantado a otra persona o entidad, incluyendo un empleado, representante o agente de VMC SUBASTAS, o que implique una falsa declaración o de que de cualquier manera tergiverse la relación del Usuario con una persona o con una entidad.' }),
      SP('30'),
    ],
  },
  {
    id: 'inhabilitacion-conducta-inapropiada',
    name: 'Account Disabled — Inappropriate Conduct',
    subject: 'Inhabilitación de cuenta',
    desc: 'Notifies the user their account was permanently disabled for offensive language or conduct on the platform, citing the corrective-measures policy clause.',
    category: 'Inhabilitación de Usuario',
    stage: 'Conducta Inapropiada',
    sections: [
      S('title', { eyebrow: '', text: 'Inhabilitación de cuenta' }),
      SP('24'),
      S('text', { text: '__{{Nombre usuario / Razón social.Ejem: Real Horizonte E.I.R.L.}}__, te informamos que tu cuenta ha sido inhabilitada por incumplir con las Condiciones y Términos de uso de nuestro servicio, los mismos que declaraste haber leído y comprendido al registrarte y en cada inicio de sesión en Plataforma. Te recordamos que todo usuario reconoce y acepta que:' }),
      SP('20'),
      S('text', { text: '**Título V. INFRACCIONES Y MEDIDAS CORRECTIVAS;**', align: 'center' }),
      SP('4'),
      S('text', { text: '**5. Respecto a su comportamiento en plataforma:**', align: 'center' }),
      SP('20'),
      S('text', { text: 'Su cuenta será inhabilitada permanentemente de verificarse que el usuario ha utilizado lenguaje ofensivo, incurra en actos de violencia, atente contra la dignidad, honor o pudor y/o la reputación de VMC SUBASTAS o alguno de sus representantes legales en cualquier medio.' }),
      SP('30'),
    ],
  },
  {
    id: 'baja-cuenta-inactividad',
    name: 'Account Deactivation Notice',
    subject: 'Tu cuenta en VMC Subastas ha sido dada de baja',
    desc: 'Notifies the user their account was deactivated and states the reason (e.g. inactivity).',
    category: 'Baja de Cuenta',
    stage: 'Confirmación',
    sections: [
      S('title', { eyebrow: '', text: 'Estimado(a) {{Nombre completo.Ejem: Pedro Cristian Rodriguez Medina}},' }),
      SP('24'),
      S('text', { text: 'Te informamos que tu cuenta en VMC Subastas ha sido dada de baja debido al siguiente motivo:' }),
      SP('14'),
      S('text', { text: '**Motivo:** {{Motivo.Ejem: Inactividad}}' }),
      SP('30'),
    ],
  },
  {
    id: 'cambio-contrasena-4panel',
    name: 'Password Change — 4Panel (Internal)',
    subject: 'Cambio de contraseña',
    desc: 'Internal-tool password-reset link for 4Panel users, valid for 30 minutes, with a plain-text fallback URL.',
    category: 'Usuarios Internos',
    stage: '4 Panel',
    sections: [
      S('title', { eyebrow: '', text: 'Cambio de contraseña' }),
      SP('24'),
      S('text', { text: 'Hola usuario de 4Panel,' }),
      SP('14'),
      S('text', { text: 'Hemos recibido una solicitud de cambio de contraseña para tu cuenta. Para continuar **debes hacer click en el siguiente botón**, recuerda que el enlace solo será válido por 30 minutos:' }),
      SP('20'),
      S('cta', { text: 'Cambiar contraseña', url: 'https://services.subastop.com/reset-password-4panel/wiTVnGmkdyfHjldX' }),
      SP('24'),
      S('text', { text: 'También puedes copiar y pegar este enlace en tu navegador:' }),
      SP('8'),
      S('text', { text: '__https://services.subastop.com/reset-password-4panel/wiTVnGmkdyfHjldX__' }),
      SP('30'),
    ],
  },
  {
    id: 'cambio-contrasena-console',
    name: 'Password Change — Console (Internal)',
    subject: 'Cambio de contraseña',
    desc: 'Internal-tool password-reset link for Console users, valid for 30 minutes, with a plain-text fallback URL.',
    category: 'Usuarios Internos',
    stage: 'Console',
    sections: [
      S('title', { eyebrow: '', text: 'Cambio de contraseña' }),
      SP('24'),
      S('text', { text: 'Hola {{Nombre usuario.Ejem: Silvana Almandoz}},' }),
      SP('14'),
      S('text', { text: 'Hemos recibido una solicitud de cambio de contraseña para tu cuenta de Console. Para continuar **debes hacer click en el siguiente botón**, recuerda que el enlace solo será válido por 30 minutos:' }),
      SP('20'),
      S('cta', { text: 'Cambiar contraseña', url: 'https://services.subastop.com/password/reset/fde337cd417db376550635ddb62e67485098b5090fdff2319b1857728a027fe5' }),
      SP('24'),
      S('text', { text: 'También puedes copiar y pegar este enlace en tu navegador:' }),
      SP('8'),
      S('text', { text: '__https://services.subastop.com/password/reset/fde337cd417db376550635ddb62e67485098b5090fdff2319b1857728a027fe5__' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-invitacion-proceso',
    name: 'Mapfre Internal Process — Invitation',
    subject: 'Proceso interno de adquisición @MAPFRE',
    desc: 'Invites MAPFRE staff to buy an offer directly at the "Valor de Restos" price without joining the live auction, with the enrollment deadline and CTA.',
    category: 'Proceso Interno Mapfre',
    stage: 'Invitación',
    leadsTo: ['mapfre-ofertas-publicadas'],
    sections: [
      S('title', { eyebrow: '', text: 'Proceso interno de adquisición' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('14'),
      S('text', { text: 'Como colaborador de MAPFRE, puedes realizar la compra de una oferta de tu interés sin necesidad de participar en el proceso En Vivo de VMC.' }),
      SP('20'),
      S('panel', { title: 'Cierre de inscripciones: **{{Fecha y hora.Ejem: Martes, 08 de Marzo 00:00 Hrs}}**', body: '' }),
      SP('16'),
      S('amount', { label: 'Valor de restos:', value: 'US$ {{X,XXX}}' }),
      SP('20'),
      S('cta', { text: 'ME INTERESA', url: 'https://www.vmcsubastas.com/login?redirect_after_to=/zona' }),
      SP('24'),
      S('text', { text: 'Ya puedes ver las ofertas __aquí__.' }),
      SP('14'),
      S('text', { text: '**Recuerda:** Puedes indicar tu interés de compra hasta las 23:59 del día anterior al día de inicio programado.' }),
      SP('14'),
      S('text', { text: 'De resultar ganador **deberás pagar el Valor de Restos**, que es el precio especial que se te brinda por colaborador de MAPFRE.' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-ofertas-publicadas',
    name: 'Mapfre Internal Process — Offers Published',
    subject: 'Proceso interno de adquisición @MAPFRE',
    desc: 'Notifies MAPFRE staff the internal offer list was published and reminds them of the interest-submission deadline.',
    category: 'Proceso Interno Mapfre',
    stage: 'Invitación',
    leadsTo: ['mapfre-participacion-registrada'],
    sections: [
      S('title', { eyebrow: '', text: 'Proceso interno de adquisición' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: '{{Nombre usuario.Ejem: Gabriel Bruno}},' }),
      SP('14'),
      S('text', { text: 'Ya puedes ver las ofertas __aquí__.' }),
      SP('14'),
      S('text', { text: '**Recuerda:** Puedes indicar tu interés de compra hasta las 23:59 del día anterior al día de inicio programado.' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-participacion-registrada',
    name: 'Mapfre Internal Process — Participation Registered',
    subject: 'Participación registrada @MAPFRE',
    desc: 'Confirms the staff member is registered to participate in the internal acquisition process for a specific vehicle.',
    category: 'Proceso Interno Mapfre',
    stage: 'Participación',
    leadsTo: ['mapfre-cierre-proceso'],
    sections: [
      S('title', { eyebrow: '', text: 'Participación registrada' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: '¡Felicitaciones {{Nombre usuario.Ejem: Gabriel Bruno}}!' }),
      SP('14'),
      S('text', { text: 'Estás participando del proceso interno de adquisición del vehículo.' }),
      SP('20'),
      S('panel', { title: '{{Placa.Ejem: ABC-123}} {{Marca y modelo.Ejem: Toyota Yaris}}', body: '{{Año.Ejem: 2014}}' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-resultados-sin-interesados',
    name: 'Mapfre Internal Process — No Interest Registered',
    subject: 'Resultados proceso de adquisición @MAPFRE',
    desc: 'Notifies that no staff member registered interest in the internal acquisition process.',
    category: 'Proceso Interno Mapfre',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Resultados proceso de adquisición' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: 'Sin registros de interesados en el proceso interno de adquisición.' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-cierre-proceso',
    name: 'Mapfre Internal Process — Closure Notice',
    subject: 'Cierre proceso de adquisición @MAPFRE',
    desc: 'Notifies participating staff that the internal acquisition process closed and results will follow shortly.',
    category: 'Proceso Interno Mapfre',
    stage: 'Cierre',
    leadsTo: ['mapfre-resultados-finales'],
    sections: [
      S('title', { eyebrow: '', text: 'Cierre proceso de adquisición' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: 'El proceso interno de adquisición de vehículos ha terminado, en breve recibirás un correo electrónico con los resultados.' }),
      SP('30'),
    ],
  },
  {
    id: 'mapfre-resultados-finales',
    name: 'Mapfre Internal Process — Final Results',
    subject: 'Resultados proceso de adquisición @MAPFRE',
    desc: 'Delivers the final results of the internal acquisition process carried out on a given date.',
    category: 'Proceso Interno Mapfre',
    stage: 'Resultado',
    sections: [
      S('title', { eyebrow: '', text: 'Resultados proceso de adquisición' }),
      SP('8'),
      S('text', { text: '**MAPFRE**', align: 'center' }),
      SP('16'),
      S('divider', {}),
      SP('20'),
      S('text', { text: 'Adjunto se encuentran los resultados del proceso interno de adquisición llevado a cabo el **{{Fecha.Ejem: 15 de agosto de 2021}}**.' }),
      SP('30'),
    ],
  },
];

export const getEmail = (id: string) => EMAILS.find((e) => e.id === id);
